# Generated by Django 4.2.5 on 2024-04-02 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COMPRA_VENTA', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=750),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fabricante',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre_producto',
            field=models.CharField(max_length=700),
        ),
    ]
